branch-defaults:
  develop:
    environment: image-filter-dev-dev
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: image-filter-dev
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
